services:
  frontend:
    image: highlights:frontend
    ports:
      - "8000:80"

  backend:
    image: highlights:backend
    environment:
      - DATABASE_URL=postgresql://highlights:a@highlights_db/highlights

  highlights_db:
    image: highlights:db
    environment:
      - POSTGRES_USER=highlights
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=highlights
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
