name: docker_push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push db
        uses: docker/build-push-action@v2
        with:
          context: ./backend/db
          push: true
          tags: hora9/blaseball-highlights:db
      -
        name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend/server
          push: true
          tags: hora9/blaseball-highlights:backend
      -
        name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hora9/blaseball-highlights:frontend
